### ISSUE TITLE
Infrastructure state remote storage

### ISSUE THREAD

**Issue by minev-dev** [opencloudtool/opencloudtool#227]
Save state files to backends:
- Local
- S3

Backend should be specified in `oct.toml`
- Local:
```toml
[project.state_backend.local]
path = "./state.json"
```
- S3:
```toml
[project.state_backend.s3]
region = "us-west-2"
bucket = "state-bucket"
```

State backend methods:
- save
- load
